appNamespace: hello-spring-dev
infraNamespace: hello-spring-dev

postgres:
  auth:
    username: postgres
    password: postgres
    database: postgres

  primary:
    persistence:
      enabled: true
      size: 5Gi

