postgres:
  auth:
    username: hello
    password: change-me
    database: hello

  primary:
    persistence:
      enabled: true
      size: 20Gi

kafka:
  replicaCount: 3

  kraft:
    enabled: true

  auth:
    enabled: true

  persistence:
    enabled: true
    size: 20Gi

  autoCreateTopicsEnable: false
