apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hello-spring
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mook3/test:hello-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 5005
              name: debug
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hello-spring
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: backend

