apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.2.0
    helm:
      valueFiles:
        - $values/argocd/values/dev.yaml
  - repoURL: https://github.com/mook3/test_react_spring.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: hello-spring-dev

  syncPolicy:
    automated:
      prune: false # don't delete DB?
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
