replicaCount: 1

kraft:
  enabled: true

auth:
  enabled: false

persistence:
  enabled: true
  size: 5Gi

image:
  registry: docker.io
  repository: apache/kafka
  tag: 4.0.0
  pullPolicy: IfNotPresent

#autoCreateTopicsEnable: true

#extraConfig: |
#  auto.create.topics.enable=true
#
# https://hub.docker.com/r/bitnami/kafka
# that site says to do this for docker:
# kafka:
#   environment:
#     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
