apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            revision: main
          - env: prod
            namespace: prod
            revision: main

  template:
    metadata:
      name: '{{env}}-platform'
    spec:
      project: platform

      source:
        repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
        targetRevision: '{{revision}}'
        path: argocd/apps/{{env}}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
